### ISSUE TITLE
Minimum number of cells required for the MAST

### ISSUE THREAD

**Issue by zhaocheng3326** [RGLab/MAST#117]
When I am doing DE test between 10 cells vs another 10 cells, I nearly can't find any DEs. After I increased the number of cells to do DE test ( including above 20 cells),  I can get about hundreds of DEGs. So may I ask is there minimum number of cell requirement for MAST?

Thanks in advance.

**Comment by amcdavid** [comment]
This question should have been posted on the [bioconductor support site](https://support.bioconductor.org/) per our README.  This is so that other people with the same question will be able to see the answer to it.  [So I reposted it and answered it there.](https://support.bioconductor.org/p/124339/#124340) . Feel free to leave comments on the bioconductor support site thread if my answer doesn't address your question.

**Comment by zhaocheng3326** [comment]
Thanks very much. It is really helpful.
