### ISSUE TITLE
Prefix melt with reshape2::

### ISSUE THREAD

**Issue by combiz** [RGLab/MAST#122]
There are a series of warnings resulting from `melt(llrt)`, `melt(lfc)`, and `melt(coefAndCI)` which are found in ZlmFit.R and ZlmFit-logFC.R .  Can be resolved with `reshape2::` prefixes or perhaps reworked with the newer `pivot_longer`?  Thanks
```
In melt(llrt) :
  The melt generic in data.table has been passed a list and will attempt to redirect to the relevant reshape2 method; please note that reshape2 is deprecated, and this redirection is now deprecated as well. To continue using melt methods from reshape2 while both libraries are attached, e.g. melt.list, you can prepend the namespace like reshape2::melt(llrt). In the next version, this warning will become an error.
```

**Comment by gfinak** [comment]
Appreciate the heads-up. We'll make the fixes.

**Comment by jacobpwagner** [comment]
Done in 94dc2619f289e4b3438f880ac874d7c290e3ac52. For now I opted to just prefix the `reshape2` namespace. `tidyr::pivot_longer` won't work out of the box because it can't handle multidimensional arrays. It's not hard to rework the methods to use `pivot_longer` or even `base` methods, but `MAST` still adds a method to the `reshape2::melt` generic for `SingleCellAssay`, so it doesn't yet make sense to completely detach it until that is renamed.
