### ISSUE TITLE
Possible Issue with Average Correlation Value from gseaAfterBoot

### ISSUE THREAD

**Issue by edvanburen** [RGLab/MAST#128]
Hello,

I have been using MAST for GSEA, and was curious to see what the estimated inter-gene correlation is for my input test sets. I have, however, been getting correlation values that are larger than 1 in magnitude from the `gseaAfterBoot` function. 

As a minimal working example, consider the example code in the MAST documentation:

```
set.seed(17)
data(vbetaFA)
vb1 = subset(vbetaFA, ncells==1)
vb1 = vb1[,freq(vb1)>.1][1:15,]
zf = zlm(~Stim.Condition, vb1)
boots = bootVcov1(zf, 5)
sets = list(A=1:5, B=3:10, C=15, D=1:5)
gsea = gseaAfterBoot(zf, boots, sets, CoefficientHypothesis('Stim.ConditionUnstim'))
```

Then, looking at the average correlation values below gives some values that are larger than one in magnitude:

`gsea@tests[,'cont','avgCor','test']`
`gsea@tests[,'disc','avgCor','test']`

Line 230 of the gseaAfterBoot function is:
vstat['avgCor', comp] <- sum(ccp[upper.tri(ccp)], na.rm=TRUE)

Perhaps it should be:

vstat['avgCor', comp] <- **mean**(ccp[upper.tri(ccp)], na.rm=TRUE)

Am I missing something? Sorry in advance if I am misinterpreting something.

Best,
Eric

**Comment by amcdavid** [comment]
Hi Eric,
Thanks for the careful report. You are correct that the correlation reported isn't the average, it's the "total".  I will note though, that the correlation, however it is accumulated isn't the correlation of the gene expression values but the correlation of the test statistics (which necessarily requires correlation in the expression values).

Your solution is correct for the correlation within the test set, but not for the null set, because of how online updates to it are performed.  It seems the solution is rather delicate, so I am inclined just to return NA for that.

I will push a fix, but as you may have gathered this functionality isn't documented, and hasn't gotten the sort of testing that other parts of the package have received.

**Comment by edvanburen** [comment]
Thanks, Andrew. Your reply makes sense and is much appreciated!

**Comment by amcdavid** [comment]
@edvanburen let me know if you find any problems with this..
