### ISSUE TITLE
Segfaults

### ISSUE THREAD

**Issue by mspivakov** [RGLab/MAST#185]
Hello!

I'm running MAST as part of the CEFCON pipeline ([cefcon/slingshot_MAST_script.R](https://github.com/WPZgithub/CEFCON/blob/0483b855830b99f28b54d7cba93d01aeeefad5dc/cefcon/slingshot_MAST_script.R)). zlm() runs fine, but I am then getting segfaults in` summary(zlmdata)` after the printed message "Combining coefficients and standard errors". Initially I thought it was to do with using too many cores on my system, but I'm getting the same error even when just asking for 1 core.

 *** caught segfault ***
address 0x14e4ec240274, cause 'invalid permissions'
*** stack smashing detected ***: <unknown> terminated
realloc(): invalid pointer

 *** caught segfault ***
address 0xf9, cause 'memory not mapped'
realloc(): invalid old size

Happy to provide input files but they are quite large so please let me know how best to share. 

Thanks!

**Comment by gfinak** [comment]
You'll notice that mast doesn't have any C++ in it's code base, other than through it's dependent packages. Without a way to reproduce your error, we'll be hard pressed to know what's going on since it could be anything from a problem with a downstream package to  some system configuration issues specific to your system.
Can you provide a minimal reproducible example?

**Comment by mspivakov** [comment]
Thanks for your reply! In this case I'll also have a go on my local machine
and report back to you. If I replicate the same issue, will send you a
reproducible example.

**Comment by mspivakov** [comment]
Yeah, it runs on my Mac, so I'll investigate what downstream packages are causing this problem on the cluster.
