### ISSUE TITLE
thresholds

### ISSUE THREAD

**Issue by alexanderaivazidis** [RGLab/MAST#67]
Hello!

I am using MAST to produce correlation networks. The method produces good results already, but there are still two questions concerning thresholding that came up in the process.

1.) The function "thresholdSCRNACountMatrix" produces non-sensical results, when I run:

thres <- thresholdSCRNACountMatrix(assay(scaRaw), nbins = 20, min_per_bin = 30)
par(mfrow=c(5,4))
plot(thres)

I have attached the corresponding plot as "image1". 
![image1](https://cloud.githubusercontent.com/assets/24434224/20969747/b53c4008-bc8a-11e6-9a06-e3d5b5494511.png)

In particular, it looks like the expression data is never bimodal even though this is clearly the case, when I test for random genes, for example:

hist(assay(scaRaw)[1,])

I have attached the corresponding plot as "image2". 
![image2](https://cloud.githubusercontent.com/assets/24434224/20969701/81a483c2-bc8a-11e6-9d9d-72dc409a9850.png)

The data I am using is from 886 samples and is already filtered to include only the 5993 most frequently expressed genes. I could not attache the whole data object "scaRaw" as an RData file, because it is too large, but I attached a subset of the 1494 most frequently expressed genes, which produces just the same problem as the large data set.
[scaRaw.RData.zip](https://github.com/RGLab/MAST/files/636694/scaRaw.RData.zip)

2.) Despite the above described problem, I can run the MAST method and produce sensible deviance results, by running:

zlmResidDE <- zlm.SingleCellAssay(~cngeneson, scaRaw, hook=deviance_residuals_hook)

However, I am wondering which thresholds the underlying Hurdle model uses to define a gene as expressed (z = 1) or not (z = 0), given I have not specified anything. In addition, how would it be possible to change the thresholds used in the Hurdle model?

Thanks in advance for your help!

Best wishes,

Alexander

**Comment by gfinak** [comment]
Seems like the bimodality you have in your data is legitimately discrete (either 0 or non-zero). There may be no need for the thresholding step. The thresholding is designed to handle bimodality where non-expressed genes are near zero. I think some additional documentation on our part might be in order to clarify this.

Best,
Greg

**Comment by amcdavid** [comment]
Yeah, I'm with Greg--you may not need to threshold the data, since there's a pretty clean break at zero.  Out of curiosity, what platform are you using?
If you want you can manually threshold with
```
scaThres = scaRaw
assay(scaThres)[assay(scaThres)<2] = 0
```
I'll update the documentation and try to add an example of this to the thresholding.

For you second question, if you don't threshold (or for that matter, if you do) the hurdle takes `z=1` if `y>0` and `z=0` if `y==0`.  The thresholding just clips some of the small, but non-zero `y`.
