### ISSUE TITLE
NAs in continuous coefficient and fold change

### ISSUE THREAD

**Issue by adnbps** [RGLab/MAST#76]
I noticed that MAST sometimes has NA for the continuous coefficient. When this happens, it also has NA for the estimated fold change. I couldn't find much in the documentation about this, but I was wondering if someone can explain it?

This is a problem for me because I'm trying to select the most differentially expressed genes using the fold change. But when I do this, I noticed that some genes are being left out, even though they have very large discrete components. The only solution is to select genes using the discrete component, ignoring the continuous component altogether, but at this point, I should just use logistic regression.

If someone can help out at all, I would really appreciate it. Thanks!

**Comment by gfinak** [comment]
The continuous component is not estimable in cases where, for example, the
gene is not expressed in some conditions.
There is not much to be done. The log fold change reported is for the
combined hurdle (discrete and continuous), so if the gene is not expressed
at all...

Greg Finak


On Jun 24, 2017 19:30, "adnbps" <notifications@github.com> wrote:

I noticed that MAST sometimes has NA for the continuous coefficient. When
this happens, it also has NA for the estimated fold change. I couldn't find
much in the documentation about this, but I was wondering if someone can
explain it?

This is a problem for me because I'm trying to select the most
differentially expressed genes using the fold change. But when I do this, I
noticed that some genes are being left out, even though they have very
large discrete components. This means I am forced to select genes using the
discrete component, ignoring the continuous component altogether. At this
point, I should just use logistic regression!

If someone can help out at all, I would really appreciate it. Thanks!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/RGLab/MAST/issues/76>, or mute the thread

**Comment by adnbps** [comment]
Ok got it.

In cases such as these, would it be possible to estimate a lower (or upper) bound on the log fold change? For example, instead of "NA" you could report "> 5".

If this doesn't make sense, then no worries! The only problem is that right now, it's a little difficult to use the fold change column for anything, since a lot of important genes have NAs.

**Comment by gfinak** [comment]
@amcdavid, thoughts on having an option in getLogFC to return the log-fold change for the discrete or continuous or combined model?

**Comment by amcdavid** [comment]
I agree with @adnbps that the NAs are annoying.  One hackish idea would be to do something akin to the stat_ell (impute)[https://github.com/RGLab/MAST/blob/master/R/predict.R] method? 

I also have a marginalized version of the hurdle model that I have been working on that will fix this issue definitively, but isn't ready for prime-time yet.

**Comment by adnbps** [comment]
Just curious if there are any plans to fix this issue in upcoming MAST releases? Thanks!
