### ISSUE TITLE
Weird behavior of statistical test for the continuous components

### ISSUE THREAD

**Issue by m113track** [RGLab/MAST#77]
I generated the following test data and performed analysis with MAST.

```
library(MAST)

#Generate toy data
testdata=rbind(c(rep(0, 40), rnorm(40, 5, 0.4)), 
                         c(rep(0, 60), rnorm(20, 5,0.4)), 
                         c(rep(0, 30), rnorm(50, 5, 0.4)))

#Add small noise so we have all non-zero expression
rtoadd=matrix(rnorm(length(testdata), 0.01, 0.001), dim(testdata)[1], dim(testdata)[2])
testdata=rtoadd+testdata

#Add row and column labels
colnames(testdata)=c(paste0('A',1:40), paste0('B',1:40))
rownames(testdata)=c('Gene1','Gene2','Gene3')

#Import into MAST
testMAst=FromMatrix(testdata)
colData(testMAst)$id=factor(c(rep("A", 40), rep("B", 40)))

#Fit and LRT
output=zlm(~id, testMAst, method="glm")
output2=summary(output, doLRT=T)$datatable

#Plot
plotme=as(testMAst, 'data.table')
ggplot(aes(x=id, y=value), data= plotme)+geom_violin()+geom_jitter()+facet_wrap(~primerid)
```

Even though the plots show that the 2 groups of cells are quite different in their expression of the genes, the hurdle P values are all almost 1. 

I thought that is fine as first because maybe human perception is not as robust as a principled statistical test but when I changed the expression for "Gene1":

```
#Generate toy data
testdata=rbind(c(rep(0, 40), rnorm(40, 100, 0.4)), c(rep(0, 60), rnorm(20, 5, 0.4)), c(rep(0, 30), rnorm(50, 5, 0.4)))
```

then the hurdle p values for all 3 genes fell to signficant values, even though the values for Gene2 and Gene3 were unchanged!

**Comment by gfinak** [comment]
The problem is that you are adding noise to the entire response vector (even the non-expressed part), and so the whole response is treated as part of the continuous component of the model. The test is therefore averaging over the entire response vector. This is the reason we threshold the non-expressed part to be exactly zero.  In your simulations, just add noise to the continuous part:
e.g.
```
testdata=rbind(c(rep(0, 40), rnorm(40, 5, 0.4)+rnorm(40,0.01,0.001)), 
					c(rep(0, 60), rnorm(20, 5,0.4)+rnorm(20,0.01,0.001)), 
					c(rep(0, 30), rnorm(50, 5, 0.4)+rnorm(50,0.01,0.001)))
```

The model will then behave  as you expect.
You will get a significant hurdle p-value for all three genes, all based on the discrete component. You will not be able to estimate a coefficient for the continuous component of the model for genes 1 and 2 because there is no expression in group A for those genes.

**Comment by m113track** [comment]
However, I was expecting the p value for the continuous component is be low, since only a small noise is added. The difference in expression between group A and B is still significantly large. But this was not the case (p>0.2). I guess the statistical test for the continuous component is more complicated than I can fanthom.

In any case, what is more worrying to me was that when I changed the expression for "Gene1" to an average of 100 in group B, the resulting p values for Gene2 and Gene3 were very different after running MAST. I was not expecting changes in values of 1 row of the gene expression matrix to affect the results for the other rows. Or does the analysis estimate variance for 1 row of genes by using information from the other rows?

**Comment by gfinak** [comment]
The model does uses empirical bayes shrinkage of the variance across genes, so yes, the variance of other genes does affect the variance estimate of individual genes. In your case there are only 3 genes, so the estimates are going to be noisy and strongly affected by the prior, on top of that your simulated data is nonsensical because non-expressed genes should be explicitly 0, not centered around 0, so the variance of the continuous component is estimated to be huge. It's no surprise you don't get a significant p-value.

**Comment by amcdavid** [comment]
@m113track if you are curious, you can turn off the empirical bayes' shrinkage with `zlm(..., ebayes=FALSE)`.  See `?zlm` . Then you get close agreement in the continuous component and a t.test.  (Not perfect agreement because we assume the sample size is large enough that the t-statistic is normally distributed).

```
output=zlm(~id, testMAst, method="glm", ebayes=FALSE)
output2=summary(output, doLRT=T)$datatable
output2[component=='C',]
## Compare to t.test
plotme[,t.test(value~id, var.equal=T), keyby=primerid]
```

All-in-all the results you get are strange because you only have three "genes" so the variance shrinkage is poorly-behaved and your "zeros" should be thresholded to be numerically zero rather than just small.
