### ISSUE TITLE
Requirement of Input data

### ISSUE THREAD

**Issue by ChangW131** [RGLab/MAST#83]
I'm wondering if log-transformed TPM (or FPKM) is a required input form for full-length scRNA-seq data. 

In addition, if working with UMI data, is it appropriate to use the raw counts or log-transformed raw counts normalized by library size within each cell? Thanks a lot!

**Comment by raphg** [comment]
You can safely used the log-transformed normalized counts by library size. We have add good results with that on 10X data.

**Comment by fbrundu** [comment]
Hi, I add to this question since the title would be the same (hope it's appropriate).

Do you think MAST can work on upper-quartile (ref.1) normalized data (instead of TPM)?
I'm using UQ to possibly reduce the influence of highly expressed genes and sparsity that you can have during library size normalization. What's your opinion on this?

Thanks for your work!

1. Bullard, James H, Elizabeth Purdom, Kasper D Hansen, and Sandrine Dudoit. 2010. “Evaluation of Statistical Methods for Normalization and Differential Expression in mRNA-Seq Experiments.” BMC Bioinformatics 11 (1). Springer Nature: 94. doi:10.1186/1471-2105-11-94.
